lint:
  files_exist:
    - assets/multiqc_config.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
  files_unchanged:
    - assets/sendmail_template.txt
    - assets/nf-core-macproqc_logo_light.png
    - docs/images/nf-core-macproqc_logo_dark.png
    - docs/images/nf-core-macproqc_logo_light.png
  multiqc_config: false
nf_core_version: 4.0.2
repository_type: pipeline
template:
  author: Julian Uszkoreit, Dirk Winkelhardt, Karin Schork, Maike Weber, Dominik Lux
  description: A workflow for the quality control of mass spectrometry-based proteomics
    analyses
  force: false
  is_nfcore: true
  name: macproqc
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
    - multiqc
    - fastqc
    - gpu
  version: 1.0.0dev
