repository_type: pipeline

nf_core_version: 4.0.2

lint:
  files_unchanged:
    - assets/sendmail_template.txt
  multiqc_config: false
  files_exist:
    - assets/multiqc_config.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config

template:
  org: nf-core
  name: macproqc
  description: A workflow for the quality control of mass spectrometry-based proteomics
    analyses
  author: Julian Uszkoreit, Dirk Winkelhardt, Karin Schork, Maike Weber, Dominik Lux
  version: 1.0.0dev
  force: true
  outdir: ./macproqc
  skip_features:
    - igenomes
    - multiqc
    - fastqc
    - gpu
  is_nfcore: true
