name: mcquac
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pip
  - setuptools
  - bioconda::openms = 3.1.0
  - bioconda::pyopenms = 3.1.0
  - conda-forge::mono ~= 6.12
  - conda-forge::compilers = 1.8.0
  - pip:
    - -r ./requirements.txt
