name: nextqcflow
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.8
  - pip
  - setuptools
  - openms
  - pyopenms  # needs to be installed by conda to link the correct OpenMS binaries
  - openms
  - mono >= 6
  - pip:
    - -r ./requirements.txt
