# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
# # TODO nf-core: Add a description of the module and list keywords
name: "qcvisualization"
description: Visualization of the collected QC metrics from the McQuaC pipeline (given as hdf5 files).
keywords:
  - proteomics
  - mass spectrometry
  - quality control
  - visualization
tools:
  - "python":
      description: "Python is a general-purpose programming language used here to parse and rewrite Comet parameter files."
      homepage: "https://www.python.org/"
      documentation: "https://docs.python.org/"
      tool_dev_url: "https://github.com/python/cpython"
      doi: ""
      licence: ["PSF-2.0"]
      identifier: null

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - hdf5_files:
        type: file
        description: Hdf5 files containing the QC metrics collected by the McQuaC pipeline
        pattern: "*.hdf5"
        ontologies:
          - edam: "http://edamontology.org/format_3590" # HDF5
  - outputdir:
      type: string
      description: Directory where the output files will be written to
  - spike_ins_table:
      type: file
      description: Table containing information on spike-ins that should be searched for
      pattern: "*.csv"
      ontologies:
        - edam: "http://edamontology.org/format_3752" # CSV

output:
  ### TODO nf-core: Add a description of all of the variables used as output
  jsons:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.json":
          type: file
          description: Plotly graphics in JSON format
          pattern: "*.json"
          ontologies:
            - edam: "http://edamontology.org/format_3464" # JSON
  htmls:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.html":
          type: file
          description: Plotly graphics in HTML format
          pattern: "*.html"
          ontologies:
            - edam: "http://edamontology.org/format_2331" # HTML
  output_tables:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.{csv,tsv,xlsx}":
          type: file
          description: Output tables in CSV, TSV, or Excel format
          pattern: "*.{csv,tsv,xlsx}"
          ontologies:
            - edam: "http://edamontology.org/format_3752" # CSV
            - edam: "http://edamontology.org/format_3475" # TSV
            - edam: "http://edamontology.org/format_3620" # Excel
  ms1_maps:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - ms1_maps: 
          type: directory
          description: Directory containing MS1 maps in PNG format
  additional_plots:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - additional_plots: 
          type: directory
          description: Directory containing additional plots in JSON or HTML format
  bruker_calibrants:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - bruker_calibrants: 
          type: directory
          description: Directory containing bruker calibrants plot in JSON or HTML format
  versions:
    - - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@KarinSchork"
maintainers:
  - "@KarinSchork"
