# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "pia_analysis"
description: Runs a PIA analysis (FDR filtering and PSM/peptide/protein inference and export) on a compiled PIA XML file, using a previously generated PIA analysis JSON configuration.
keywords:
  - proteomics
  - protein inference
  - fdr
  - pia
tools:
  - "pia":
      description: "PIA is a toolbox for MS based protein inference and identification
        analysis."
      homepage: "None"
      documentation: "None"
      tool_dev_url: "None"
      doi: ""
      licence: ["BSD-3-clause"]
      identifier: biotools:pia_d

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - pia_xml:
        type: file
        description: Compiled PIA intermediate file, as produced by PIA_COMPILEXML
        pattern: "*.pia.xml"
    - pia_json:
        type: file
        description: PIA analysis configuration file, as produced by PIA_CONFIGURE
        pattern: "*.pia.json"

output:
  psms:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.piaExport-PSMs.mzTab":
          type: file
          description: PSM-level export (optional - not produced if PSM export was disabled in the analysis configuration)
          pattern: "*.piaExport-PSMs.mzTab"
  peptides:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.piaExport-peptides.csv":
          type: file
          description: Peptide-level export (optional - not produced if peptide export was disabled in the analysis configuration)
          pattern: "*.piaExport-peptides.csv"
  proteins:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.piaExport-proteins.mzTab":
          type: file
          description: Protein-level export (optional - not produced if protein export was disabled in the analysis configuration)
          pattern: "*.piaExport-proteins.mzTab"
  versions_pia:
    - - "${task.process}":
          type: string
          description: The name of the process
      - "pia":
          type: string
          description: The name of the tool
      - "pia --version":
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - pia:
          type: string
          description: The name of the tool
      - pia --version:
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@julianu"
maintainers:
  - "@julianu"
