#!/bin/bash
# Calls FeatureFinderMultiplex and passes down all arguments

# FeatureFinderMultiplex is located next to this script
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

${SCRIPT_DIR}/openms/usr/bin/FeatureFinderMultiplex $@
