name: Build and Deploy Documentation

on:
  pull_request:
    types:
      - closed
    branches:
      - dev
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-docs:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Nextflow
        uses: nf-core/setup-nextflow@b4ec1bc7c16a94435159de94a05253542fddf6ef # v3

      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install dependencies
        run: pip install mkdocs-material nf-core

      - name: Generate parameters page from schema
        run: nf-core pipelines schema docs --output docs/parameters.md nextflow_schema.json

      - name: Deploy documentation to GitHub Pages
        run: mkdocs gh-deploy --force
